### ISSUE TITLE
Optional dependency of counsel-projectile

### ISSUE THREAD

**Issue by leungbk** [emacs-taskrunner/ivy-taskrunner#1]
https://github.com/emacs-taskrunner/ivy-taskrunner/blob/68b8277554a8126e2f79fbe7463bddd9ceae46d0/ivy-taskrunner.el#L261

`featurep` is preferable to `package-installed-p` here since not everyone uses `package.el`.

https://github.com/emacs-taskrunner/ivy-taskrunner/blob/68b8277554a8126e2f79fbe7463bddd9ceae46d0/ivy-taskrunner.el#L262-L269

People who use `counsel-projectile` will tend to have `counsel-projectile-mode` on, which I believe remaps `projectile-switch-project` to `counsel-projectile-switch-project`. So this seems unnecessary to me.

But if there's another reason to handle it this way, then something like

``` emacs-lisp
(declare-function counsel-projectile-switch-project "ext:counsel-projectile")

(defun ivy-taskrunner--check-if-in-project ()
  "Check if the currently visited buffer is in a project.
If it is not, prompt the user to select a project"
  ;; If we are not in a project, ask the user to switch to one
  (if (not (projectile-project-p))
      ;; If counsel is intalled, use that, otherwise use the default
      ;; projectile-switch-project interface. The command returns
      (if (featurep 'counsel-projectile)
          (progn
            (require 'counsel-projectile)
            (counsel-projectile-switch-project))
        (projectile-switch-project))
    t))

```

would be needed to placate the byte-compiler if I wanted to install this package using something like the Guix package manager.

**Comment by sehnsucht13** [comment]
I see. Thanks a lot for the heads up! I will fix it ASAP in this repo and use `featurep` in the helm frontend as well.

I am mostly a helm user so I use `helm-projectile` and that does not have its own mode like `counsel-projectile` seems to have so it has to use the `helm-projectile-switch-project` command instead. If that command is not used then calling `projectile-switch-project` will simply use the default ido interface for projectile.

**Comment by sehnsucht13** [comment]
Update:
I have decided to go with following code:

```emacs-lisp
(declare-function counsel-projectile-switch-project "ext:counsel-projectile")

(defun ivy-taskrunner--check-if-in-project ()
  "Check if the currently visited buffer is in a project.
If it is not, prompt the user to select a project"
  ;; If we are not in a project, ask the user to switch to one
  (if (not (projectile-project-p))
      ;; If counsel is intalled, use that, otherwise use the default
      ;; projectile-switch-project interface.
      (if (require 'counsel-projectile nil 'noerror)
          ;; This code will never be reached unless ivy-projectile is
          ;; installed but this is necessary in order to silence the
          ;; bytecompiler warning
          (when (fboundp 'counsel-projectile-switch-project)
            (counsel-projectile-switch-project))
        (projectile-switch-project))
    t))
```
The call to `package-installed-p` has been removed and instead I use a `require` with an extra argument which will not produce an error if the package is not found.

I would like to keep the existing behaviour. The way I see it, some users might have the mode on(the majority of them most likely) but there might be some who do not and this will help them out. Either way, the users who do have this mode on will not be affected at all by this behaviour.

I will push this to master soon. Please let me know if the bytecompile issue is gone for you. If you have any other comments or issues then please let me know! You can either post here or create another issue if it is for a separate topic.

EDIT: This has been pushed to master

**Comment by leungbk** [comment]
It seems good now, thanks!

https://github.com/emacs-taskrunner/ivy-taskrunner/blob/75d8d67cfe3c29663fe0f5508a887adf40ed5162/ivy-taskrunner.el#L8

You should list here `(ivy "0.12.0") (projectile "2.0.0")` also.

https://github.com/emacs-taskrunner/ivy-taskrunner/blob/75d8d67cfe3c29663fe0f5508a887adf40ed5162/ivy-taskrunner.el#L74

I don't think it hurts to `(require 'projectile)` here, though I haven't gotten any errors without it.

https://github.com/emacs-taskrunner/ivy-taskrunner/blob/75d8d67cfe3c29663fe0f5508a887adf40ed5162/ivy-taskrunner.el#L281

You shouldn't need `fboundp` now that you have `declare-function` as well as the relevant function after the `require`.

**Comment by sehnsucht13** [comment]
Thanks for the suggestions! `projectile` is required inside of the `taskrunner` library but I will add it in this package as well just in case.

**Comment by sehnsucht13** [comment]
Fixes have been implemented. Thanks a lot for your advice and for the code review. I really appreciate it!

If there is anything else you can think of in terms of improvements then feel free to add it to this thread. Otherwise, feel free to close the issue if you are satisfied.

**Comment by leungbk** [comment]
Thanks for your hard work on the project.
